import assert from "node:assert/strict";
import { createInitialLearnerState, deriveSkillState, isCategoryUnlocked } from "../src/learning/mastery";
import { buildReviewPlan } from "../src/learning/reviewPlan";
import { CloudflareVoiceAssessmentProvider } from "../src/learning/cloudflareVoiceProvider";
import { assessVoiceSafely, mayUseSpecificReadingDiagnosis, type VoiceAssessmentProvider } from "../src/learning/voiceAssessment";
import type { AttemptRecord, ExerciseCategory } from "../src/learning/types";

function attempt(category: ExerciseCategory, sessionId: string, attemptedAt: string, outcome: AttemptRecord["outcome"] = "correct", index = 0): AttemptRecord { return { itemId: `${category}-${sessionId}-${index}`, category, sessionId, attemptedAt, outcome }; }
function run(name: string, fn: () => void | Promise<void>) { return Promise.resolve().then(fn).then(() => console.log(`✓ ${name}`)).catch((error) => { console.error(`✗ ${name}`); throw error; }); }

await run("only reading units are unlocked for a new learner", () => { const state = createInitialLearnerState(); assert.equal(isCategoryUnlocked("reading_units", state), true); assert.equal(isCategoryUnlocked("vowels_sukun", state), false); });
await run("the next category requires mastery or excellence, not consolidation", () => { const state = createInitialLearnerState(); state.skills.reading_units = { ...state.skills.reading_units, level: "consolidation" }; assert.equal(isCategoryUnlocked("vowels_sukun", state), false); state.skills.reading_units = { ...state.skills.reading_units, level: "mastery" }; assert.equal(isCategoryUnlocked("vowels_sukun", state), true); });
await run("a delayed success clears the scheduled stability review", () => { const first = new Date("2026-08-24T08:00:00.000Z"); const later = new Date(first.getTime() + 13 * 60 * 60 * 1000); const oneSuccess = deriveSkillState("reading_units", [attempt("reading_units", "s1", first.toISOString())]); assert.equal(oneSuccess.delayedCheckPassed, false); assert.equal(oneSuccess.nextReviewAt, new Date(first.getTime() + 12 * 60 * 60 * 1000).toISOString()); const delayed = deriveSkillState("reading_units", [attempt("reading_units", "s1", first.toISOString()), attempt("reading_units", "s2", later.toISOString())]); assert.equal(delayed.delayedCheckPassed, true); assert.equal(delayed.nextReviewAt, undefined); });
await run("mastery requires multiple contexts and a delayed check", () => { const base = new Date("2026-08-20T08:00:00.000Z"); const attempts: AttemptRecord[] = [attempt("reading_units", "s1", base.toISOString(), "correct", 0)]; const delayedStart = base.getTime() + 13 * 60 * 60 * 1000; for (let i = 1; i < 60; i += 1) attempts.push(attempt("reading_units", `s${(i % 3) + 1}`, new Date(delayedStart + i * 60 * 1000).toISOString(), "correct", i)); const skill = deriveSkillState("reading_units", attempts); assert.equal(skill.stableAcrossContexts, true); assert.equal(skill.delayedCheckPassed, true); assert.equal(skill.level, "mastery"); assert.notEqual(deriveSkillState("reading_units", attempts.map((record) => ({ ...record, sessionId: "single" }))).level, "mastery"); });
await run("review planning cannot surface a locked category", () => { const state = createInitialLearnerState(); state.skills.reading_units = { ...state.skills.reading_units, level: "mastery" }; state.skills.vowels_sukun = { ...state.skills.vowels_sukun, level: "progression" }; state.attempts = Array.from({ length: 8 }, (_, i) => attempt("shaddah", "locked", new Date(2026, 7, 24, i).toISOString(), "incorrect", i)); assert.notEqual(buildReviewPlan(state, new Date("2026-08-24T20:00:00.000Z")).category, "shaddah"); });
await run("a due delayed review is selected among unlocked skills", () => { const state = createInitialLearnerState(); state.skills.reading_units = { ...state.skills.reading_units, level: "mastery", stableAcrossContexts: true, delayedCheckPassed: true }; state.skills.vowels_sukun = { ...state.skills.vowels_sukun, level: "progression", stableAcrossContexts: true, nextReviewAt: "2026-08-24T08:00:00.000Z" }; const plan = buildReviewPlan(state, new Date("2026-08-24T20:00:00.000Z")); assert.equal(plan.category, "vowels_sukun"); assert.equal(plan.dueNow, true); });

const voiceRequest = { itemId: "test", referenceText: "reference", audio: new Blob(["audio"], { type: "audio/webm" }) };
await run("voice assessment degrades to manual control without a provider", async () => { assert.equal((await assessVoiceSafely(null, voiceRequest)).status, "unavailable"); });
await run("voice provider failures degrade to manual control", async () => { const provider: VoiceAssessmentProvider = { assess: async () => { throw new Error("provider down"); } }; assert.equal((await assessVoiceSafely(provider, voiceRequest)).status, "unavailable"); });
await run("unvalidated or low-confidence diagnoses remain observational", async () => { const provider: VoiceAssessmentProvider = { assess: async () => ({ provider: "test", recognized: true, specificReadingError: { kind: "vowel", confidence: 0.89, validatedByItqan: true } }) }; const guidance = await assessVoiceSafely(provider, voiceRequest); assert.equal(guidance.status, "observed"); assert.equal(mayUseSpecificReadingDiagnosis(guidance.result!), false); });
await run("only validated diagnoses at the confidence gate may be specific", async () => { const provider: VoiceAssessmentProvider = { assess: async () => ({ provider: "test", recognized: true, specificReadingError: { kind: "vowel", confidence: 0.9, validatedByItqan: true } }) }; const guidance = await assessVoiceSafely(provider, voiceRequest); assert.equal(guidance.status, "specific_diagnosis"); assert.equal(mayUseSpecificReadingDiagnosis(guidance.result!), true); });
await run("Cloudflare adapter posts the controlled reference and audio", async () => { let seenUrl = ""; let seenBody: FormData | null = null; const provider = new CloudflareVoiceAssessmentProvider({ endpoint: "/test-voice", fetchImpl: (async (input, init) => { seenUrl = String(input); seenBody = init?.body as FormData; return new Response(JSON.stringify({ provider: "cloudflare-shell", recognized: false }), { status: 200, headers: { "content-type": "application/json" } }); }) as typeof fetch }); const result = await provider.assess({ ...voiceRequest, localeHint: "ar-SA" }); assert.equal(seenUrl, "/test-voice"); assert.equal(seenBody?.get("itemId"), "test"); assert.equal(seenBody?.get("referenceText"), "reference"); assert.equal(seenBody?.get("localeHint"), "ar-SA"); assert.ok(seenBody?.get("audio") instanceof Blob); assert.equal(result.provider, "cloudflare-shell"); assert.equal(result.recognized, false); });
await run("Cloudflare adapter rejects invalid audio before network", async () => { let fetchCalls = 0; const provider = new CloudflareVoiceAssessmentProvider({ fetchImpl: (async () => { fetchCalls += 1; return new Response("unexpected"); }) as typeof fetch }); await assert.rejects(() => provider.assess({ ...voiceRequest, audio: new Blob([], { type: "audio/webm" }) }), /audio is empty/); await assert.rejects(() => provider.assess({ ...voiceRequest, audio: new Blob(["audio"], { type: "text/plain" }) }), /audio type is unsupported/); await assert.rejects(() => provider.assess({ ...voiceRequest, audio: new Blob([new Uint8Array(8 * 1024 * 1024 + 1)], { type: "audio/webm" }) }), /audio is too large/); assert.equal(fetchCalls, 0); });
await run("Cloudflare adapter requires a JSON response content type", async () => { const payload = JSON.stringify({ provider: "test", recognized: false }); const missing = new CloudflareVoiceAssessmentProvider({ fetchImpl: (async () => new Response(payload, { status: 200 })) as typeof fetch }); await assert.rejects(() => missing.assess(voiceRequest), /non-JSON response/); const text = new CloudflareVoiceAssessmentProvider({ fetchImpl: (async () => new Response(payload, { status: 200, headers: { "content-type": "text/plain" } })) as typeof fetch }); await assert.rejects(() => text.assess(voiceRequest), /non-JSON response/); const vendorJson = new CloudflareVoiceAssessmentProvider({ fetchImpl: (async () => new Response(payload, { status: 200, headers: { "content-type": "application/vnd.itqan.voice+json; charset=utf-8" } })) as typeof fetch }); assert.equal((await vendorJson.assess(voiceRequest)).provider, "test"); });
await run("Cloudflare adapter rejects malformed assessment responses", async () => { const provider = new CloudflareVoiceAssessmentProvider({ fetchImpl: (async () => new Response(JSON.stringify({ provider: "broken" }), { status: 200, headers: { "content-type": "application/json" } })) as typeof fetch }); await assert.rejects(() => provider.assess(voiceRequest), /Invalid voice assessment response/); });
await run("Cloudflare adapter rejects out-of-range confidence", async () => { const provider = new CloudflareVoiceAssessmentProvider({ fetchImpl: (async () => new Response(JSON.stringify({ provider: "test", recognized: true, confidence: 4.2 }), { status: 200, headers: { "content-type": "application/json" } })) as typeof fetch }); await assert.rejects(() => provider.assess(voiceRequest), /Invalid voice assessment response/); });
await run("Cloudflare adapter rejects untrusted diagnosis shapes", async () => { const provider = new CloudflareVoiceAssessmentProvider({ fetchImpl: (async () => new Response(JSON.stringify({ provider: "test", recognized: true, specificReadingError: { kind: "invented", confidence: 1, validatedByItqan: true } }), { status: 200, headers: { "content-type": "application/json" } })) as typeof fetch }); await assert.rejects(() => provider.assess(voiceRequest), /Invalid voice assessment response/); });
await run("Cloudflare adapter rejects failed endpoint responses", async () => { const provider = new CloudflareVoiceAssessmentProvider({ fetchImpl: (async () => new Response("unavailable", { status: 503 })) as typeof fetch }); await assert.rejects(() => provider.assess(voiceRequest), /503/); });
await run("Cloudflare adapter aborts a stalled request and safety falls back to manual control", async () => { let sawAbort = false; const fetchImpl = ((_: RequestInfo | URL, init?: RequestInit) => new Promise<Response>((_, reject) => { const signal = init?.signal; signal?.addEventListener("abort", () => { sawAbort = true; reject(new DOMException("Aborted", "AbortError")); }, { once: true }); })) as typeof fetch; const provider = new CloudflareVoiceAssessmentProvider({ fetchImpl, timeoutMs: 5 }); const guidance = await assessVoiceSafely(provider, voiceRequest); assert.equal(sawAbort, true); assert.equal(guidance.status, "unavailable"); });
await run("Cloudflare adapter rejects invalid timeout configuration", () => { assert.throws(() => new CloudflareVoiceAssessmentProvider({ timeoutMs: 0 }), /timeout must be positive/); });

console.log("Learning policy tests passed.");